-- MySQL Script generated by MySQL Workbench
-- Sat Sep 11 12:34:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema equaly_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `equaly_db` ;

-- -----------------------------------------------------
-- Schema equaly_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `equaly_db` DEFAULT CHARACTER SET utf8 ;
USE `equaly_db` ;

-- -----------------------------------------------------
-- Table `equaly_db`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`departments` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`departments` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `department_name_UNIQUE` (`department_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equaly_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`users` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `user_name` VARCHAR(32) NOT NULL,
  `user_password` VARCHAR(32) NOT NULL,
  `user_email` VARCHAR(64) NOT NULL,
  `user_token` VARCHAR(32) NOT NULL,
  `user_last_login` DATETIME NOT NULL,
  `user_type` ENUM('EVENT_OPENER', 'QUALITY_INSPECTOR', 'RNC_REPORTER', 'ADMIN') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) ,
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) ,
  INDEX `fk_user_department_idx` (`department_id` ASC) ,
  CONSTRAINT `fk_user_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `equaly_db`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equaly_db`.`occur_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`occur_types` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`occur_types` (
  `occur_type_id` INT NOT NULL AUTO_INCREMENT,
  `occur_type_name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`occur_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equaly_db`.`occur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`occurs` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`occurs` (
  `occur_id` INT NOT NULL AUTO_INCREMENT,
  `occur_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `occur_prior` ENUM('LOW', 'MEDIUM', 'HIGH', 'DEFAULT') NOT NULL,
  `occur_date` DATETIME NOT NULL,
  `occur_occured` DATE NOT NULL,
  `occur_inspector` INT NOT NULL,
  `occur_author` VARCHAR(64) NOT NULL,
  `occur_author_document` VARCHAR(18) NULL,
  `occur_author_contact` VARCHAR(128) NULL,
  `occur_nf` VARCHAR(32) NULL,
  `occur_title` VARCHAR(64) NOT NULL,
  `occur_description` VARCHAR(256) NOT NULL,
  `occur_status` ENUM('OCCUR_OPENED', 'OCCUR_CLOSED') NOT NULL,
  `occur_closed_at` DATETIME NULL,
  `occur_feedback` VARCHAR(256) NULL,
  `occur_feedback_view` TINYINT NOT NULL,
  `occur_rnc_opened` TINYINT NOT NULL,
  PRIMARY KEY (`occur_id`),
  INDEX `fk_occur_occur_type_idx` (`occur_type_id` ASC) ,
  INDEX `fk_occur_user_idx` (`user_id` ASC) ,
  INDEX `fk_occur_inspector` (`occur_inspector` ASC) ,
  CONSTRAINT `fk_occur_occur_type1`
    FOREIGN KEY (`occur_type_id`)
    REFERENCES `equaly_db`.`occur_types` (`occur_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_occur_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `equaly_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equaly_db`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`files` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`files` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `occur_id` INT NOT NULL,
  `file_content` LONGBLOB NOT NULL,
  `file_name` VARCHAR(128) NOT NULL,
  `file_format` VARCHAR(64) NOT NULL,
  `file_type` VARCHAR(128) NOT NULL,
  `file_size` INT NOT NULL,
  `file_date` DATETIME NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_file_occur1_idx` (`occur_id` ASC) ,
  CONSTRAINT `fk_file_occur1`
    FOREIGN KEY (`occur_id`)
    REFERENCES `equaly_db`.`occurs` (`occur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equaly_db`.`rnc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `equaly_db`.`rnc` ;

CREATE TABLE IF NOT EXISTS `equaly_db`.`rncs` (
  `rnc_id` INT NOT NULL AUTO_INCREMENT,
  `occur_id` INT NOT NULL,
  `rnc_inspector` INT NOT NULL,
  `rnc_reporter` INT NOT NULL,
  `rnc_5w` JSON NULL,
  `rnc_preview_date` DATE NULL,
  `rnc_report_date` DATETIME NULL,
  `rnc_validation_date` DATETIME NULL,
  `rnc_finalization` VARCHAR(256) NULL,
  `rnc_finalization_date` DATETIME NULL,
  `rnc_eficacy` VARCHAR(256) NULL,
  `rnc_closed_at` DATETIME NULL,
  `rnc_status` ENUM('RNC_OPENED', 'RNC_WAITING_PA_VALIDATION', 'RNC_PA_REPROVED', 'RNC_WAITING_FINALIZATION', 'RNC_WAITING_CLOSE', 'RNC_CLOSE_REPROVED', 'RNC_CLOSED') NULL,
  PRIMARY KEY (`rnc_id`),
  INDEX `fk_rnc_occur1_idx` (`occur_id` ASC) ,
  INDEX `fk_rnc_occur_inspector_idx` (`rnc_inspector` ASC) ,
  CONSTRAINT `fk_rnc_occur_id`
    FOREIGN KEY (`occur_id`)
    REFERENCES `equaly_db`.`occurs` (`occur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rnc_occur_inspector`
    FOREIGN KEY (`rnc_inspector`)
    REFERENCES `equaly_db`.`occurs` (`occur_inspector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `occur_types` (`occur_type_name`) VALUES
('Data divergente ou avançada'),
('Embalagem com vazamento ou tampa quebrada'),
('Erro de montagem de carga'),
('Incompatibilidade com o pedido'),
('Outros ocorridos'),
('Pedido com Produto trocado ou Cancelado'),
('Pedido expirado (rede)'),
('Problema com código de barras da caixa'),
('Produto avariado pela transportadora'),
('Produto com cheiro, cor, sabor ou textura diferente'),
('Produto com corpo estranho (pelo, cabelo, pontos pretos, etc.)'),
('Produto com Lote e data apagados'),
('Produto com Pote amassado'),
('Produto com selo, lacre ou filme rompido'),
('Produto Cristalizado ou Açucarado'),
('Produto embolorado'),
('Produto sem pedido'),
('Produto Vencido');