-- SCHEMA: equaly_adm
-- OBSERVATION: RUN THIS SCRIPT AS USER EQUALY_ADMIN

-- DROP SCHEMA IF EXISTS equaly_adm ;


CREATE SCHEMA IF NOT EXISTS equaly_adm
    AUTHORIZATION equaly_admin;

COMMENT ON SCHEMA equaly_adm
    IS 'eQualy Administrator Database Schema';

GRANT USAGE ON SCHEMA equaly_adm TO equaly;

GRANT ALL ON SCHEMA equaly_adm TO equaly_admin;

BEGIN;

CREATE TABLE IF NOT EXISTS "equaly_adm"."DEPARTMENT" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
    "CORPORATION_ID" BIGINT NOT NULL,
	"NAME" VARCHAR(64) NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_BY" VARCHAR(128) NOT NULL,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
    "UPDATED_BY" VARCHAR(128) DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL,
    "DISABLED_BY" VARCHAR(128) DEFAULT NULL,
	UNIQUE ("CORPORATION_ID","NAME")
);

ALTER TABLE "equaly_adm"."DEPARTMENT" DROP CONSTRAINT IF EXISTS "DEPARTMENT_FK_CORPORATION_ID";
ALTER TABLE "equaly_adm"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "equaly_iam"."CORPORATION"("ID");


DROP TYPE IF EXISTS "equaly_adm".USER_ROLE CASCADE;
DROP TYPE IF EXISTS "equaly_adm".USER_SUBROLE CASCADE;
CREATE TYPE "equaly_adm".USER_ROLE AS ENUM('EVENT_OPENER','QUALITY_INSPECTOR','RNC_REPORTER','SUPERUSER');
CREATE TYPE "equaly_adm".USER_SUBROLE AS ENUM('MASTER_ACCESS','COMMON_ACCESS');

CREATE TABLE IF NOT EXISTS "equaly_adm"."USER" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"CORPORATION_ID" BIGINT NOT NULL,
	"DEPARTMENT_ID" BIGINT NOT NULL,
	"LOGIN" VARCHAR(64) NOT NULL UNIQUE,
	"NAME" VARCHAR(256) NOT NULL,
	"NICKNAME" VARCHAR(128) NOT NULL,
	"EMAIL" VARCHAR(256) NOT NULL UNIQUE,
	"PASSWORD" VARCHAR(72) NOT NULL,
	"ROLE" "equaly_adm".USER_ROLE ARRAY NOT NULL,
	"SUBROLE" "equaly_adm".USER_SUBROLE ARRAY NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"FIRST_ACCESS" BOOLEAN NOT NULL DEFAULT TRUE,
	"LAST_LOGIN_AT" TIMESTAMP DEFAULT NULL,
	"AVATAR_ID" VARCHAR DEFAULT NULL,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_BY" VARCHAR(128) NOT NULL,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
    "UPDATED_BY" VARCHAR(128) DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL,
    "DISABLED_BY" VARCHAR(128) DEFAULT NULL
);

ALTER TABLE "equaly_adm"."USER" DROP CONSTRAINT IF EXISTS "USER_FK_CORPORATION_ID";
ALTER TABLE "equaly_adm"."USER" ADD CONSTRAINT "USER_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "equaly_iam"."CORPORATION"("ID");

ALTER TABLE "equaly_adm"."USER" DROP CONSTRAINT IF EXISTS "USER_FK_DEPARTMENT_ID";
ALTER TABLE "equaly_adm"."USER" ADD CONSTRAINT "USER_FK_DEPARTMENT_ID" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "equaly_adm"."DEPARTMENT"("ID");


CREATE TABLE IF NOT EXISTS "equaly_adm"."OCCUR_TYPE" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
    "CORPORATION_ID" BIGINT NOT NULL,
	"NAME" VARCHAR(128) NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_BY" VARCHAR(128) NOT NULL,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
    "UPDATED_BY" VARCHAR(128) DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL,
    "DISABLED_BY" VARCHAR(128) DEFAULT NULL,
	UNIQUE ("CORPORATION_ID","NAME")
);

ALTER TABLE "equaly_adm"."OCCUR_TYPE" DROP CONSTRAINT IF EXISTS "OCCUR_TYPE_FK_CORPORATION_ID";
ALTER TABLE "equaly_adm"."OCCUR_TYPE" ADD CONSTRAINT "OCCUR_TYPE_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "equaly_iam"."CORPORATION"("ID");

COMMIT;