-- SCHEMA: equaly_iam
-- OBSERVATION: RUN THIS SCRIPT AS USER EQUALY_ADMIN

-- DROP SCHEMA IF EXISTS equaly_iam ;

CREATE SCHEMA IF NOT EXISTS equaly_iam
    AUTHORIZATION equaly_admin;

COMMENT ON SCHEMA equaly_iam
    IS 'eQualy IAM Database Schema';

GRANT USAGE ON SCHEMA equaly_iam TO equaly;

GRANT ALL ON SCHEMA equaly_iam TO equaly_admin;

BEGIN;

CREATE TABLE IF NOT EXISTS "equaly_iam"."CORPORATION" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"NAME" VARCHAR(128) NOT NULL UNIQUE,
	"ALIAS" VARCHAR(64) NOT NULL UNIQUE,
	"DOCUMENT" CHAR(14) NOT NULL UNIQUE,
	"CONTACT" VARCHAR(256) NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CREATED_BY" VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS "equaly_iam"."CREDENTIAL" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"CORPORATION_ID" BIGINT NOT NULL,
	"VALUE" VARCHAR NOT NULL UNIQUE,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"CREATED_BY" VARCHAR(128) NOT NULL
);

ALTER TABLE "equaly_iam"."CREDENTIAL" DROP CONSTRAINT IF EXISTS "CREDENTIAL_FK_CORPORATION_ID";
ALTER TABLE "equaly_iam"."CREDENTIAL" ADD CONSTRAINT "CREDENTIAL_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "equaly_iam"."CORPORATION"("ID");

COMMIT;