BEGIN;

CREATE SCHEMA IF NOT EXISTS "CORPORATION";

CREATE TABLE IF NOT EXISTS "CORPORATION"."CORPORATION" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"NAME" VARCHAR(128) NOT NULL UNIQUE,
	"ALIAS" VARCHAR(64) NOT NULL UNIQUE,
	"DOCUMENT" CHAR(14) NOT NULL UNIQUE,
	"CONTACT" VARCHAR(256) NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "CORPORATION"."KEY" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"CORPORATION_ID" BIGINT NOT NULL,
	"VALUE" VARCHAR NOT NULL UNIQUE,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "CORPORATION"."DEPARTMENT" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"NAME" VARCHAR(64) NOT NULL UNIQUE,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "CORPORATION"."CORPORATION_DEPARTMENT" (
	"CORPORATION_ID" BIGINT NOT NULL,
	"DEPARTMENT_ID" BIGINT NOT NULL,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

ALTER TABLE "CORPORATION"."KEY" DROP CONSTRAINT IF EXISTS "KEY_FK_CORPORATION_ID";
ALTER TABLE "CORPORATION"."KEY" ADD CONSTRAINT "KEY_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "CORPORATION"."CORPORATION"("ID");

ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" DROP CONSTRAINT IF EXISTS "ID";
ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" ADD CONSTRAINT "ID" PRIMARY KEY("CORPORATION_ID","DEPARTMENT_ID");

ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" DROP CONSTRAINT IF EXISTS "CORPORATION_DEPARTMENT_FK_CORPORATION_ID";
ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" ADD CONSTRAINT "CORPORATION_DEPARTMENT_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "CORPORATION"."CORPORATION"("ID");

ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" DROP CONSTRAINT IF EXISTS "CORPORATION_DEPARTMENT_FK_DEPARTMENT_ID";
ALTER TABLE "CORPORATION"."CORPORATION_DEPARTMENT" ADD CONSTRAINT "CORPORATION_DEPARTMENT_FK_DEPARTMENT_ID" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "CORPORATION"."DEPARTMENT"("ID");

COMMIT;