CREATE SCHEMA IF NOT EXISTS "CORPORATION";


CREATE TABLE IF NOT EXISTS "CORPORATION"."CORPORATION" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"NAME" VARCHAR(128) NOT NULL UNIQUE,
	"ALIAS" VARCHAR(64) NOT NULL UNIQUE,
	"DOCUMENT" CHAR(14) NOT NULL UNIQUE,
	"CONTACT" VARCHAR(256) NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"APPLICATION_KEY" VARCHAR NOT NULL,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "CORPORATION"."KEY" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"VALUE" VARCHAR NOT NULL UNIQUE,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

ALTER TABLE "CORPORATION"."CORPORATION" DROP CONSTRAINT IF EXISTS "CORPORATION_FK_APPLICATION_KEY";
ALTER TABLE "CORPORATION"."CORPORATION" ADD CONSTRAINT "CORPORATION_FK_APPLICATION_KEY" FOREIGN KEY ("APPLICATION_KEY") REFERENCES "CORPORATION"."KEY"("VALUE");