ALTER TABLE "USER"."USER" DROP CONSTRAINT IF NOT EXISTS "USER_FK_CORPORATION_ID";

ALTER TABLE "USER"."USER" ADD COLUMN "CORPORATION_ID" BIGINT NOT NULL;

ALTER TABLE "USER"."USER" ADD CONSTRAINT "USER_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "CORPORATION"."CORPORATION"("ID");