BEGIN;

CREATE SCHEMA IF NOT EXISTS "USER";

DROP TYPE IF EXISTS "USER".USER_ROLE CASCADE;
DROP TYPE IF EXISTS "USER".USER_SUBROLE CASCADE;
CREATE TYPE "USER".USER_ROLE AS ENUM('EVENT_OPENER','QUALITY_INSPECTOR','RNC_REPORTER','IT_MANAGER');
CREATE TYPE "USER".USER_SUBROLE AS ENUM('ADMIN','DEFAULT');

CREATE TABLE IF NOT EXISTS "USER"."USER" (
	"ID" BIGSERIAL CHECK ("ID" > 0) PRIMARY KEY,
	"CORPORATION_ID" BIGINT NOT NULL,
	"DEPARTMENT_ID" BIGINT NOT NULL,
	"LOGIN" VARCHAR(64) NOT NULL UNIQUE,
	"NAME" VARCHAR(256) NOT NULL,
	"NICKNAME" VARCHAR(128) NOT NULL,
	"EMAIL" VARCHAR(256) NOT NULL UNIQUE,
	"PASSWORD" VARCHAR(72) NOT NULL,
	"ROLE" "USER".USER_ROLE NOT NULL,
	"SUBROLE" "USER".USER_SUBROLE NOT NULL,
	"IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
	"FIRST_ACCESS" BOOLEAN NOT NULL DEFAULT TRUE,
	"LAST_LOGIN_AT" TIMESTAMP DEFAULT NULL,
	"AVATAR_ID" VARCHAR DEFAULT NULL,
	"CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT NULL,
	"DISABLED_AT" TIMESTAMP DEFAULT NULL
);

ALTER TABLE "USER"."USER" DROP CONSTRAINT IF EXISTS "USER_FK_CORPORATION_ID";
ALTER TABLE "USER"."USER" ADD CONSTRAINT "USER_FK_CORPORATION_ID" FOREIGN KEY ("CORPORATION_ID") REFERENCES "CORPORATION"."CORPORATION"("ID");

ALTER TABLE "USER"."USER" DROP CONSTRAINT IF EXISTS "USER_FK_DEPARTMENT_ID";
ALTER TABLE "USER"."USER" ADD CONSTRAINT "USER_FK_DEPARTMENT_ID" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "CORPORATION"."DEPARTMENT"("ID");

COMMIT;